baseURL = 'http://shipilka-gathering.github.io'
languageCode = 'ja'
title = 'シピルカくん集会'

[taxonomies]
  tag = "tags"
  category = "categories"

defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false

[languages]
[languages.ja]
languageName = "日本語"
weight = 1

[languages.en]
languageName = "English"
weight = 2
